In [2]:
import pandas as pd

In [5]:
import pandas as pd
data = {
    "car": ["Honda city","Hyundai Creta","Maruti swift",
            "Tata Nexon","Toyota Innova","Honda Amaze","Kia seltos","Maruti Baleno"],
    "company": ["Honda","Hyundai","Maruti","Tata","Toyota","Honda","Kia","Maruti"],
    "year": [2022,2023,2011,2023,2022,2020,2024,2011],
    "price":[1200000,1500000,700000,1100000,2200000,650000,1600000,800000],
    "Mileage":[18,17,23,19,14,20,16,22],
    "Fuel":["Petrol","Diesel","Petrol","Diesel","Diesel","Petrol","Petrol","Petrol"],
    "Rating":[4.5,4.3,4.2,4.4,4.6,4.0,4.5,4.1]

}
df = pd.DataFrame(data)

In [6]:
df

             car  company  year    price  Mileage    Fuel  Rating
0     Honda city    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
2   Maruti swift   Maruti  2011   700000       23  Petrol     4.2
3     Tata Nexon     Tata  2023  1100000       19  Diesel     4.4
4  Toyota Innova   Toyota  2022  2200000       14  Diesel     4.6
5    Honda Amaze    Honda  2020   650000       20  Petrol     4.0
6     Kia seltos      Kia  2024  1600000       16  Petrol     4.5
7  Maruti Baleno   Maruti  2011   800000       22  Petrol     4.1

In [7]:
df.head()

             car  company  year    price  Mileage    Fuel  Rating
0     Honda city    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
2   Maruti swift   Maruti  2011   700000       23  Petrol     4.2
3     Tata Nexon     Tata  2023  1100000       19  Diesel     4.4
4  Toyota Innova   Toyota  2022  2200000       14  Diesel     4.6

In [8]:
df.tail()

             car company  year    price  Mileage    Fuel  Rating
3     Tata Nexon    Tata  2023  1100000       19  Diesel     4.4
4  Toyota Innova  Toyota  2022  2200000       14  Diesel     4.6
5    Honda Amaze   Honda  2020   650000       20  Petrol     4.0
6     Kia seltos     Kia  2024  1600000       16  Petrol     4.5
7  Maruti Baleno  Maruti  2011   800000       22  Petrol     4.1

In [9]:
df.shape

(8, 7)

In [10]:
df.columns

Index(['car', 'company', 'year', 'price', 'Mileage', 'Fuel', 'Rating'], dtype='object')

In [11]:
df.dtypes

car         object
company     object
year         int64
price        int64
Mileage      int64
Fuel        object
Rating     float64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   car      8 non-null      object
 1   company  8 non-null      object
 2   year     8 non-null      int64
 3   price    8 non-null      int64
 4   Mileage  8 non-null      int64
 5   Fuel     8 non-null      object
 6   Rating   8 non-null      float64
dtypes: float64(1), int64(3), object(3)
memory usage: 580.0+ bytes

In [15]:
df[["car"]]

             car
0     Honda city
1  Hyundai Creta
2   Maruti swift
3     Tata Nexon
4  Toyota Innova
5    Honda Amaze
6     Kia seltos
7  Maruti Baleno

In [17]:
df[["car","price"]]

             car    price
0     Honda city  1200000
1  Hyundai Creta  1500000
2   Maruti swift   700000
3     Tata Nexon  1100000
4  Toyota Innova  2200000
5    Honda Amaze   650000
6     Kia seltos  1600000
7  Maruti Baleno   800000

In [18]:
df.iloc[0:3]

             car  company  year    price  Mileage    Fuel  Rating
0     Honda city    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
2   Maruti swift   Maruti  2011   700000       23  Petrol     4.2

In [19]:
df.loc[0:1]

             car  company  year    price  Mileage    Fuel  Rating
0     Honda city    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3

In [21]:
expensive_car = df[df["price"]>1000000]
print(expensive_car)

             car  company  year    price  Mileage    Fuel  Rating
0     Honda city    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
3     Tata Nexon     Tata  2023  1100000       19  Diesel     4.4
4  Toyota Innova   Toyota  2022  2200000       14  Diesel     4.6
6     Kia seltos      Kia  2024  1600000       16  Petrol     4.5

In [22]:
sorted_cars = df.sort_values(by="price")
print(sorted_cars)

             car  company  year    price  Mileage    Fuel  Rating
5    Honda Amaze    Honda  2020   650000       20  Petrol     4.0
2   Maruti swift   Maruti  2011   700000       23  Petrol     4.2
7  Maruti Baleno   Maruti  2011   800000       22  Petrol     4.1
3     Tata Nexon     Tata  2023  1100000       19  Diesel     4.4
0     Honda city    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
6     Kia seltos      Kia  2024  1600000       16  Petrol     4.5
4  Toyota Innova   Toyota  2022  2200000       14  Diesel     4.6

In [23]:
from numpy import average
average_price = df["price"].mean()
print(average_price)

1218750.0

In [24]:
print("Higehest price:",df["price"].max())
print("Lowest Price:",df["price"].min() )

Higehest price: 2200000
Lowest Price: 650000

In [25]:
df.describe()

              year         price    Mileage    Rating
count     8.000000  8.000000e+00   8.000000  8.000000
mean   2019.500000  1.218750e+06  18.625000  4.325000
std       5.371884  5.304563e+05   3.020761  0.212132
min    2011.000000  6.500000e+05  14.000000  4.000000
25%    2017.750000  7.750000e+05  16.750000  4.175000
50%    2022.000000  1.150000e+06  18.500000  4.350000
75%    2023.000000  1.525000e+06  20.500000  4.500000
max    2024.000000  2.200000e+06  23.000000  4.600000

In [26]:
print(df["company"].value_counts())

company
Honda      2
Maruti     2
Hyundai    1
Tata       1
Toyota     1
Kia        1
Name: count, dtype: int64

In [28]:
print(df["Fuel"].unique())

['Petrol' 'Diesel']

In [29]:
df.isnull().sum()

car        0
company    0
year       0
price      0
Mileage    0
Fuel       0
Rating     0
dtype: int64

In [33]:
sample = pd.DataFrame({
    "car":["Honda","Tata","Maruti","Hyundai"],
    "price":[1200000,None,700000,1500000],
    "Mileage":[18,19,None,17]

})
print(sample)

       car      price  Mileage
0    Honda  1200000.0     18.0
1     Tata        NaN     19.0
2   Maruti   700000.0      NaN
3  Hyundai  1500000.0     17.0

In [39]:
sample["price"] = sample["price"].fillna(
    sample["price"].mean()
)
sample["Mileage"]=sample["Mileage"].fillna(
    sample["Mileage"].mean()
)
print(sample)

       car         price  Mileage
0    Honda  1.200000e+06     18.0
1     Tata  1.133333e+06     19.0
2   Maruti  7.000000e+05     18.0
3  Hyundai  1.500000e+06     17.0

In [46]:
# Re-initialize df from data to recover from the overwritten state
df = pd.DataFrame(data)

# Correctly drop duplicates and display df
df = df.drop_duplicates()

In [47]:
df

             car  company  year    price  Mileage    Fuel  Rating
0     Honda city    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
2   Maruti swift   Maruti  2011   700000       23  Petrol     4.2
3     Tata Nexon     Tata  2023  1100000       19  Diesel     4.4
4  Toyota Innova   Toyota  2022  2200000       14  Diesel     4.6
5    Honda Amaze    Honda  2020   650000       20  Petrol     4.0
6     Kia seltos      Kia  2024  1600000       16  Petrol     4.5
7  Maruti Baleno   Maruti  2011   800000       22  Petrol     4.1